Public Class Form1
    Private Sub ÁREADEUNACIRCUNFERENCIAToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNACIRCUNFERENCIAToolStripMenuItem.Click
        Form2.Show()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNRECTÁNGULOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNRECTÁNGULOToolStripMenuItem.Click
        Form3.Show()
        Form2.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNTRIÁNGULOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNTRIÁNGULOToolStripMenuItem.Click
        Form4.Show()
        Form2.Close()
        Form3.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNCUADRADOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNCUADRADOToolStripMenuItem.Click
        Form5.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNAELIPSEToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNAELIPSEToolStripMenuItem.Click
        Form6.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNTRAPECIOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNTRAPECIOToolStripMenuItem.Click
        Form7.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNROMBOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNROMBOToolStripMenuItem.Click
        Form8.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNPENTÁGONOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNPENTÁGONOToolStripMenuItem.Click
        Form9.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNHEXÁGONOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNHEXÁGONOToolStripMenuItem.Click
        Form10.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub VOLUMENDEUNCILINDROToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles VOLUMENDEUNCILINDROToolStripMenuItem.Click
        Form11.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub VOLUMENDEUNCONOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles VOLUMENDEUNCONOToolStripMenuItem.Click
        Form12.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub VOLUMENDEUNAPIRAMIDERECTANGULARToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles VOLUMENDEUNAPIRAMIDERECTANGULARToolStripMenuItem.Click
        Form13.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub
    Private Sub VOLUMENDEUNPRISMAPENTAGONALToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles VOLUMENDEUNPRISMAPENTAGONALToolStripMenuItem.Click
        Form14.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNCUADRADOTRIÁNGULOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNCUADRADOTRIÁNGULOToolStripMenuItem.Click
        Form15.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNRECTÁNGULOELIPSEToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNRECTÁNGULOELIPSEToolStripMenuItem.Click
        Form16.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNRECTÁNGULOTRIÁNGULOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNRECTÁNGULOTRIÁNGULOToolStripMenuItem.Click
        Form17.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNTRAPECIOCIRCUNFERENCIAToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNTRAPECIOCIRCUNFERENCIAToolStripMenuItem.Click
        Form18.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNTRIÁNGULOEQUILATEROCIRCUNFERENCIAToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNTRIÁNGULOEQUILATEROCIRCUNFERENCIAToolStripMenuItem.Click
        Form19.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNCUADRADOCIRCUNFERENCIAToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNCUADRADOCIRCUNFERENCIAToolStripMenuItem.Click
        Form20.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub DIFERENCIADEUNRECTÁNGULO2TRIÁNGULOSToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DIFERENCIADEUNRECTÁNGULO2TRIÁNGULOSToolStripMenuItem.Click
        Form21.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNAPIRAMIDERECTANGULARToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNAPIRAMIDERECTANGULARToolStripMenuItem.Click
        Form22.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNTRONCODECONOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNTRONCODECONOToolStripMenuItem.Click
        Form23.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNPRISMAPENTAGONALToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNPRISMAPENTAGONALToolStripMenuItem.Click
        Form24.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNCILINDROToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNCILINDROToolStripMenuItem.Click
        Form25.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNPRISMAHEXAGONALToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNPRISMAHEXAGONALToolStripMenuItem.Click
        Form26.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNPRISMARECTANGULARToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNPRISMARECTANGULARToolStripMenuItem.Click
        Form27.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form28.Close()
    End Sub

    Private Sub ÁREADEUNCONOToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ÁREADEUNCONOToolStripMenuItem.Click
        Form28.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Form4.Show()
        Form2.Close()
        Form3.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        Form7.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        Form9.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
        Form11.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        Form14.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
        Form15.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button8_Click(sender As Object, e As EventArgs) Handles Button8.Click
        Form19.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Form25.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form26.Close()
        Form27.Close()
        Form28.Close()
    End Sub

    Private Sub Button9_Click(sender As Object, e As EventArgs) Handles Button9.Click
        Form27.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form28.Close()
    End Sub

    Private Sub Button10_Click(sender As Object, e As EventArgs) Handles Button10.Click
        Form28.Show()
        Form2.Close()
        Form3.Close()
        Form4.Close()
        Form5.Close()
        Form6.Close()
        Form7.Close()
        Form8.Close()
        Form9.Close()
        Form10.Close()
        Form11.Close()
        Form12.Close()
        Form13.Close()
        Form14.Close()
        Form15.Close()
        Form16.Close()
        Form17.Close()
        Form18.Close()
        Form19.Close()
        Form20.Close()
        Form21.Close()
        Form22.Close()
        Form23.Close()
        Form24.Close()
        Form25.Close()
        Form26.Close()
        Form27.Close()
    End Sub
End Class
